INSERT INTO gem_colors (name, color) VALUES
    ('Absolution', 'RED'),
    ('Infernal Cry', 'RED'),
    ('Precision', 'GREEN'),
    ('Alchemist''s Mark', 'GREEN'),
    ('Ambush', 'GREEN'),
    ('Ancestral Warchief', 'RED'),
    ('Ancestral Blademaster', 'RED'),
    ('Ancestral Cry', 'RED'),
    ('Fist of War Support', 'RED'),
    ('Anger', 'RED'),
    ('Animate Guardian', 'RED'),
    ('Animate Weapon', 'GREEN'),
    ('Arc', 'BLUE'),
    ('Arcane Cloak', 'BLUE'),
    ('Arctic Armour', 'GREEN'),
    ('Creeping Frost', 'BLUE'),
    ('Artillery Ballista', 'GREEN'),
    ('Assassin''s Mark', 'BLUE'),
    ('Backstab', 'GREEN'),
    ('Ball Lightning', 'BLUE'),
    ('Barrage', 'GREEN'),
    ('Battlemage''s Cry', 'RED'),
    ('Bear Trap', 'GREEN'),
    ('Berserk', 'RED'),
    ('Void Sphere', 'BLUE'),
    ('Blade Blast', 'GREEN'),
    ('Blade Trap', 'GREEN'),
    ('Blade Vortex', 'GREEN'),
    ('Bladefall', 'GREEN'),
    ('Bladestorm', 'RED'),
    ('Blast Rain', 'GREEN'),
    ('Blight', 'BLUE'),
    ('Blink Arrow', 'GREEN'),
    ('Blood Offering', 'BLUE'),
    ('Blood Rage', 'GREEN'),
    ('Flesh and Stone', 'RED'),
    ('Blood and Sand', 'RED'),
    ('Perforate', 'RED'),
    ('Reap', 'RED'),
    ('War Banner', 'RED'),
    ('Unearth', 'GREEN'),
    ('Bone Offering', 'BLUE'),
    ('Boneshatter', 'RED'),
    ('Arcanist Brand', 'BLUE'),
    ('Burning Arrow', 'GREEN'),
    ('Armageddon Brand', 'BLUE'),
    ('Chain Hook', 'RED'),
    ('Blade Flurry', 'GREEN'),
    ('Charged Dash', 'GREEN'),
    ('Sigil of Power', 'BLUE'),
    ('Clarity', 'BLUE'),
    ('Cleave', 'RED'),
    ('Kinetic Blast', 'BLUE'),
    ('Cobra Lash', 'GREEN'),
    ('Vaal Impurity of Ice', 'GREEN'),
    ('Icicle Mine', 'BLUE'),
    ('Purity of Ice', 'GREEN'),
    ('Cold Snap', 'BLUE'),
    ('Conductivity', 'BLUE'),
    ('Storm Brand', 'BLUE'),
    ('Consecrated Path', 'RED'),
    ('Contagion', 'BLUE'),
    ('Conversion Trap', 'BLUE'),
    ('Convocation', 'BLUE'),
    ('Cremation', 'GREEN'),
    ('Bodyswap', 'BLUE'),
    ('Plague Bearer', 'GREEN'),
    ('Corrupting Fever', 'RED'),
    ('Cyclone', 'GREEN'),
    ('Damage Infusion', 'BLUE'),
    ('Malevolence', 'BLUE'),
    ('Dark Pact', 'BLUE'),
    ('Bane', 'BLUE'),
    ('Decoy Totem', 'RED'),
    ('Defiance Banner', 'RED'),
    ('Desecrate', 'GREEN'),
    ('Despair', 'BLUE'),
    ('Destructive Link', 'BLUE'),
    ('Determination', 'RED'),
    ('Detonate Dead', 'GREEN'),
    ('Devouring Totem', 'RED'),
    ('Discharge', 'BLUE'),
    ('Discipline', 'BLUE'),
    ('Crackling Lance', 'BLUE'),
    ('Divine Ire', 'BLUE'),
    ('Dominating Blow', 'RED'),
    ('Hexblast', 'BLUE'),
    ('Lacerate', 'GREEN'),
    ('Double Strike', 'GREEN'),
    ('Dual Strike', 'GREEN'),
    ('Earthquake', 'RED'),
    ('Elemental Hit', 'GREEN'),
    ('Elemental Projectiles', 'BLUE'),
    ('Elemental Weakness', 'BLUE'),
    ('Blazing Salvo', 'BLUE'),
    ('Endurance Charge on Melee Stun Support', 'RED'),
    ('Tectonic Slam', 'RED'),
    ('Enduring Cry', 'RED'),
    ('Energy Blade', 'BLUE'),
    ('Enfeeble', 'BLUE'),
    ('Ensnaring Arrow', 'GREEN'),
    ('Envy', 'BLUE'),
    ('Essence Drain', 'BLUE'),
    ('Ethereal Knives', 'GREEN'),
    ('Incinerate', 'BLUE'),
    ('Explosive Arrow', 'GREEN'),
    ('Explosive Concoction', 'GREEN'),
    ('Exsanguinate', 'RED'),
    ('Eye of Winter', 'BLUE'),
    ('Scorching Ray', 'BLUE'),
    ('Vaal Impurity of Fire', 'RED'),
    ('Purity of Fire', 'RED'),
    ('Fire Trap', 'GREEN'),
    ('Fire Weapon', 'BLUE'),
    ('Fireball', 'BLUE'),
    ('Firestorm', 'BLUE'),
    ('Flame Wall', 'BLUE'),
    ('Flame Dash', 'BLUE'),
    ('Flame Link', 'RED'),
    ('Holy Flame Totem', 'RED'),
    ('Flame Surge', 'BLUE'),
    ('Flameblast', 'BLUE'),
    ('Flamethrower Trap', 'GREEN'),
    ('Flammability', 'BLUE'),
    ('Flesh Offering', 'BLUE'),
    ('Flicker Strike', 'GREEN'),
    ('Forbidden Rite', 'BLUE'),
    ('Freezing Pulse', 'BLUE'),
    ('Frenzy', 'GREEN'),
    ('Frost Blades', 'GREEN'),
    ('Frostbolt', 'BLUE'),
    ('Vortex', 'BLUE'),
    ('Frost Bomb', 'BLUE'),
    ('Winter Orb', 'BLUE'),
    ('Frost Shield', 'BLUE'),
    ('Frost Wall', 'BLUE'),
    ('Frostbite', 'BLUE'),
    ('Galvanic Field', 'BLUE'),
    ('General''s Cry', 'RED'),
    ('Glacial Cascade', 'BLUE'),
    ('Glacial Hammer', 'RED'),
    ('Grace', 'GREEN'),
    ('Ground Slam', 'RED'),
    ('Haste', 'GREEN'),
    ('Hatred', 'GREEN'),
    ('Heavy Strike', 'RED'),
    ('Herald of Agony', 'GREEN'),
    ('Herald of Ash', 'RED'),
    ('Herald of Blood', 'RED'),
    ('Herald of Ice', 'GREEN'),
    ('Herald of Purity', 'RED'),
    ('Herald of Thunder', 'BLUE'),
    ('Ice Crash', 'RED'),
    ('Frostblink', 'BLUE'),
    ('Ice Nova', 'BLUE'),
    ('Ice Shot', 'GREEN'),
    ('Siphoning Trap', 'BLUE'),
    ('Ice Spear', 'BLUE'),
    ('Ice Trap', 'GREEN'),
    ('Icefire', 'BLUE'),
    ('Ignite', 'BLUE'),
    ('Wintertide Brand', 'BLUE'),
    ('Immortal Call', 'RED'),
    ('Splitting Steel', 'GREEN'),
    ('Infernal Blow', 'RED'),
    ('Wildfire', 'BLUE'),
    ('Infernal Sweep', 'RED'),
    ('Intimidating Cry', 'RED'),
    ('Intuitive Link', 'GREEN'),
    ('Kinetic Bolt', 'BLUE'),
    ('Lancing Steel', 'GREEN'),
    ('Leap Slam', 'RED'),
    ('Lightning Arrow', 'GREEN'),
    ('Lightning Channel', 'BLUE'),
    ('Lightning Circle', 'BLUE'),
    ('Lightning Conduit', 'BLUE'),
    ('Stormblast Mine', 'BLUE'),
    ('Vaal Impurity of Lightning', 'BLUE'),
    ('Purity of Lightning', 'BLUE'),
    ('Lightning Strike', 'GREEN'),
    ('Lightning Tendrils', 'BLUE'),
    ('Lightning Spire Trap', 'BLUE'),
    ('Lightning Trap', 'BLUE'),
    ('Lightning Warp', 'BLUE'),
    ('Rolling Magma', 'BLUE'),
    ('Penance Brand', 'BLUE'),
    ('Pestilent Strike', 'GREEN'),
    ('Manabond', 'BLUE'),
    ('Mirror Arrow', 'GREEN'),
    ('Molten Shell', 'RED'),
    ('Molten Strike', 'RED'),
    ('Pyroclast Mine', 'BLUE'),
    ('Phase Run', 'GREEN'),
    ('Shield Charge', 'RED'),
    ('Sunder', 'RED'),
    ('Flammable Shot', 'GREEN'),
    ('Orb of Storms', 'BLUE'),
    ('Petrified Blood', 'RED'),
    ('Seismic Trap', 'GREEN'),
    ('Pride', 'RED'),
    ('Poacher''s Mark', 'GREEN'),
    ('Caustic Arrow', 'GREEN'),
    ('Poisonous Concoction', 'GREEN'),
    ('Power Siphon', 'BLUE'),
    ('Protective Link', 'RED'),
    ('Puncture', 'GREEN'),
    ('Punishment', 'RED'),
    ('Dread Banner', 'RED'),
    ('Wave of Conviction', 'BLUE'),
    ('Purity of Elements', 'BLUE'),
    ('Dash', 'GREEN'),
    ('Steelskin', 'RED'),
    ('Rage Vortex', 'RED'),
    ('Rain of Arrows', 'GREEN'),
    ('Toxic Rain', 'GREEN'),
    ('Raise Spectre', 'BLUE'),
    ('Raise Zombie', 'BLUE'),
    ('Rallying Cry', 'RED'),
    ('Reave', 'GREEN'),
    ('Reckoning', 'RED'),
    ('Rejuvenation Totem', 'RED'),
    ('Rending Steel', 'RED'),
    ('Righteous Fire', 'BLUE'),
    ('Righteous Lightning', 'BLUE'),
    ('Riposte', 'GREEN'),
    ('Riptide', 'BLUE'),
    ('Purifying Flame', 'BLUE'),
    ('Scourge Arrow', 'GREEN'),
    ('Searing Bond', 'RED'),
    ('Seismic Cry', 'RED'),
    ('Shadow Blades', 'GREEN'),
    ('Shattering Steel', 'GREEN'),
    ('Shield Crush', 'RED'),
    ('Shock Nova', 'BLUE'),
    ('Shockwave Totem', 'RED'),
    ('Shrapnel Ballista', 'GREEN'),
    ('Galvanic Arrow', 'GREEN'),
    ('Explosive Trap', 'GREEN'),
    ('Siege Ballista', 'GREEN'),
    ('Brand Recall', 'BLUE'),
    ('Summon Skitterbots', 'BLUE'),
    ('Withering Step', 'GREEN'),
    ('Smite', 'RED'),
    ('Smoke Mine', 'GREEN'),
    ('Venom Gyre', 'GREEN'),
    ('Snipe', 'GREEN'),
    ('Sniper''s Mark', 'GREEN'),
    ('Soul Link', 'BLUE'),
    ('Soulrend', 'BLUE'),
    ('Spark', 'BLUE'),
    ('Spectral Helix', 'GREEN'),
    ('Zealotry', 'BLUE'),
    ('Spellslinger', 'BLUE'),
    ('Earthshatter', 'RED'),
    ('Spirit Offering', 'BLUE'),
    ('Split Arrow', 'GREEN'),
    ('Static Strike', 'RED'),
    ('Static Tether', 'BLUE'),
    ('Storm Burst', 'BLUE'),
    ('Storm Call', 'BLUE'),
    ('Storm Rain', 'GREEN'),
    ('Stormbind', 'BLUE'),
    ('Summon Carrion Golem', 'BLUE'),
    ('Summon Chaos Golem', 'BLUE'),
    ('Summon Flame Golem', 'RED'),
    ('Summon Ice Golem', 'GREEN'),
    ('Summon Lightning Golem', 'BLUE'),
    ('Summon Raging Spirit', 'BLUE'),
    ('Summon Reaper', 'BLUE'),
    ('Summon Holy Relic', 'BLUE'),
    ('Summon Stone Golem', 'RED'),
    ('Summon Skeletons', 'BLUE'),
    ('Summon Skeletons Channelled', 'BLUE'),
    ('Added Chaos Damage Support', 'BLUE'),
    ('Awakened Added Chaos Damage Support', 'BLUE'),
    ('Added Cold Damage Support', 'GREEN'),
    ('Awakened Added Cold Damage Support', 'GREEN'),
    ('Added Fire Damage Support', 'RED'),
    ('Awakened Added Fire Damage Support', 'RED'),
    ('Added Lightning Damage Support', 'BLUE'),
    ('Awakened Added Lightning Damage Support', 'BLUE'),
    ('Additional Accuracy Support', 'GREEN'),
    ('Second Wind Support', 'GREEN'),
    ('Empower Support', 'RED'),
    ('Awakened Empower Support', 'RED'),
    ('Enhance Support', 'GREEN'),
    ('Awakened Enhance Support', 'GREEN'),
    ('Swift Assembly Support', 'GREEN'),
    ('Enlighten Support', 'BLUE'),
    ('Awakened Enlighten Support', 'BLUE'),
    ('Unbound Ailments Support', 'BLUE'),
    ('Awakened Ancestral Call Support', 'RED'),
    ('Arcane Surge Support', 'BLUE'),
    ('Archmage Support', 'BLUE'),
    ('Arrow Nova Support', 'GREEN'),
    ('Awakened Arrow Nova Support', 'GREEN'),
    ('Divine Blessing Support', 'RED'),
    ('Barrage Support', 'GREEN'),
    ('Behead Support', 'RED'),
    ('Blasphemy Support', 'BLUE'),
    ('Awakened Blasphemy Support', 'BLUE'),
    ('Blind Support', 'GREEN'),
    ('Block Chance Reduction Support', 'GREEN'),
    ('Arrogance Support', 'RED'),
    ('Bloodlust Support', 'RED'),
    ('Bloodthirst Support', 'RED'),
    ('Shockwave Support', 'RED'),
    ('Bonechill Support', 'BLUE'),
    ('Brutality Support', 'RED'),
    ('Awakened Brutality Support', 'RED'),
    ('Awakened Burning Damage Support', 'RED'),
    ('Infernal Legion Support', 'BLUE'),
    ('Cast On Critical Strike Support', 'GREEN'),
    ('Awakened Cast On Critical Strike Support', 'GREEN'),
    ('Cast when Damage Taken Support', 'RED'),
    ('Cast on Death Support', 'GREEN'),
    ('Cast on Melee Kill Support', 'RED'),
    ('Cast when Stunned Support', 'BLUE'),
    ('Cast while Channelling Support', 'BLUE'),
    ('Awakened Cast While Channelling Support', 'BLUE'),
    ('Chain Support', 'GREEN'),
    ('Awakened Chain Support', 'GREEN'),
    ('Chance to Bleed Support', 'RED'),
    ('Chance to Flee Support', 'GREEN'),
    ('Combustion Support', 'BLUE'),
    ('Chance to Poison Support', 'GREEN'),
    ('Withering Touch Support', 'GREEN'),
    ('Charged Mines Support', 'BLUE'),
    ('Cluster Traps Support', 'GREEN'),
    ('Cold Penetration Support', 'GREEN'),
    ('Awakened Cold Penetration Support', 'GREEN'),
    ('Cold to Fire Support', 'RED'),
    ('Concentrated Effect Support', 'BLUE'),
    ('Controlled Destruction Support', 'BLUE'),
    ('Awakened Controlled Destruction Support', 'BLUE'),
    ('Critical Strike Affliction Support', 'GREEN'),
    ('Cruelty Support', 'RED'),
    ('Culling Strike Support', 'GREEN'),
    ('Hextouch Support', 'BLUE'),
    ('Awakened Hextouch Support', 'BLUE'),
    ('Hypothermia Support', 'GREEN'),
    ('Deadly Ailments Support', 'GREEN'),
    ('Awakened Deadly Ailments Support', 'GREEN'),
    ('Vile Toxins Support', 'GREEN'),
    ('Decay Support', 'BLUE'),
    ('Earthbreaker Support', 'RED'),
    ('Efficacy Support', 'BLUE'),
    ('Elemental Focus Support', 'BLUE'),
    ('Awakened Elemental Focus Support', 'BLUE'),
    ('Elemental Penetration Support', 'BLUE'),
    ('Elemental Proliferation Support', 'BLUE'),
    ('Energy Leech Support', 'BLUE'),
    ('Faster Attacks Support', 'GREEN'),
    ('Faster Casting Support', 'BLUE'),
    ('Faster Projectiles Support', 'GREEN'),
    ('Fire Penetration Support', 'RED'),
    ('Awakened Fire Penetration Support', 'RED'),
    ('Focused Ballista Support', 'GREEN'),
    ('Fork Support', 'GREEN'),
    ('Awakened Fork Support', 'GREEN'),
    ('Fortify Support', 'RED'),
    ('Ice Bite Support', 'GREEN'),
    ('Charged Traps Support', 'GREEN'),
    ('Mirage Archer Support', 'GREEN'),
    ('Generosity Support', 'RED'),
    ('Awakened Generosity Support', 'RED'),
    ('Greater Multiple Projectiles Support', 'GREEN'),
    ('Awakened Greater Multiple Projectiles Support', 'GREEN'),
    ('Greater Volley Support', 'GREEN'),
    ('Unleash Support', 'BLUE'),
    ('Intensify Support', 'BLUE'),
    ('Ignite Proliferation Support', 'BLUE'),
    ('Immolate Support', 'BLUE'),
    ('Impale Support', 'GREEN'),
    ('Increased Area of Effect Support', 'BLUE'),
    ('Awakened Increased Area of Effect Support', 'BLUE'),
    ('Burning Damage Support', 'RED'),
    ('Increased Critical Damage Support', 'BLUE'),
    ('Increased Critical Strikes Support', 'BLUE'),
    ('Increased Duration Support', 'RED'),
    ('Iron Grip Support', 'RED'),
    ('Iron Will Support', 'RED'),
    ('Item Quantity Support', 'RED'),
    ('Item Rarity Support', 'BLUE'),
    ('Knockback Support', 'RED'),
    ('Lesser Multiple Projectiles Support', 'GREEN'),
    ('Life Gain on Hit Support', 'RED'),
    ('Life Leech Support', 'RED'),
    ('Lifetap Support', 'RED'),
    ('Lightning Penetration Support', 'BLUE'),
    ('Awakened Lightning Penetration Support', 'BLUE'),
    ('Maim Support', 'RED'),
    ('Mana Leech Support', 'GREEN'),
    ('Mark On Hit Support', 'GREEN'),
    ('Damage on Full Life Support', 'RED'),
    ('Melee Physical Damage Support', 'RED'),
    ('Awakened Melee Physical Damage Support', 'RED'),
    ('Melee Splash Support', 'RED'),
    ('Awakened Melee Splash Support', 'RED'),
    ('Minefield Support', 'BLUE'),
    ('Minion Damage Support', 'BLUE'),
    ('Awakened Minion Damage Support', 'BLUE'),
    ('Meat Shield Support', 'BLUE'),
    ('Predator Support', 'BLUE'),
    ('Minion Life Support', 'BLUE'),
    ('Feeding Frenzy Support', 'BLUE'),
    ('Minion Speed Support', 'BLUE'),
    ('Eternal Blessing Support', 'RED'),
    ('Multiple Totems Support', 'RED'),
    ('Multiple Traps Support', 'GREEN'),
    ('Spell Echo Support', 'BLUE'),
    ('Multistrike Support', 'RED'),
    ('Awakened Multistrike Support', 'RED'),
    ('Onslaught Support', 'GREEN'),
    ('Innervate Support', 'BLUE'),
    ('Overcharge Support', 'BLUE'),
    ('Volley Support', 'GREEN'),
    ('Vicious Projectiles Support', 'GREEN'),
    ('Physical to Lightning Support', 'BLUE'),
    ('Pierce Support', 'GREEN'),
    ('Point Blank Support', 'GREEN'),
    ('Power Charge On Critical Support', 'BLUE'),
    ('Pinpoint Support', 'BLUE'),
    ('Pulverise Support', 'RED'),
    ('Nightblade Support', 'GREEN'),
    ('Rage Support', 'RED'),
    ('Ballista Totem Support', 'RED'),
    ('Swiftbrand Support', 'BLUE'),
    ('Swift Affliction Support', 'GREEN'),
    ('Less Duration Support', 'RED'),
    ('Inspiration Support', 'RED'),
    ('Blastchain Mine Support', 'BLUE'),
    ('High-Impact Mine Support', 'BLUE'),
    ('Return Projectiles Support', 'GREEN'),
    ('Ruthless Support', 'RED'),
    ('Close Combat Support', 'GREEN'),
    ('Slower Projectiles Support', 'GREEN'),
    ('Spell Cascade Support', 'BLUE'),
    ('Awakened Spell Cascade Support', 'BLUE'),
    ('Awakened Spell Echo Support', 'BLUE'),
    ('Spell Totem Support', 'RED'),
    ('Ancestral Call Support', 'RED'),
    ('Split Projectiles Support', 'GREEN'),
    ('Infused Channelling Support', 'BLUE'),
    ('Stun Support', 'RED'),
    ('Elemental Army Support', 'BLUE'),
    ('Summon Phantasm Support', 'BLUE'),
    ('Awakened Swift Affliction Support', 'GREEN'),
    ('Trap Support', 'GREEN'),
    ('Trap and Mine Damage Support', 'GREEN'),
    ('Advanced Traps Support', 'GREEN'),
    ('Trinity Support', 'BLUE'),
    ('Lesser Reduced Mana Cost Support', 'RED'),
    ('Awakened Unbound Ailments Support', 'BLUE'),
    ('Awakened Unleash Support', 'BLUE'),
    ('Urgent Orders Support', 'RED'),
    ('Awakened Vicious Projectiles Support', 'GREEN'),
    ('Void Manipulation Support', 'GREEN'),
    ('Awakened Void Manipulation Support', 'GREEN'),
    ('Elemental Damage with Attacks Support', 'RED'),
    ('Awakened Elemental Damage with Attacks Support', 'RED'),
    ('Sweep', 'RED'),
    ('Tempest Shield', 'BLUE'),
    ('Temporal Chains', 'GREEN'),
    ('Temporal Rift', 'GREEN'),
    ('Spectral Shield Throw', 'GREEN'),
    ('Spectral Throw', 'GREEN'),
    ('Tornado', 'GREEN'),
    ('Tornado Shot', 'GREEN'),
    ('Ancestral Protector', 'RED'),
    ('Touch of God', 'RED'),
    ('Vaal Ancestral Warchief', 'RED'),
    ('Vaal Arc', 'BLUE'),
    ('Vaal Blade Vortex', 'GREEN'),
    ('Vaal Blight', 'BLUE'),
    ('Vaal Burning Arrow', 'GREEN'),
    ('Vaal Clarity', 'BLUE'),
    ('Vaal Cold Snap', 'BLUE'),
    ('Vaal Cyclone', 'GREEN'),
    ('Vaal Detonate Dead', 'GREEN'),
    ('Vaal Discipline', 'BLUE'),
    ('Vaal Double Strike', 'GREEN'),
    ('Vaal Earthquake', 'RED'),
    ('Vaal Fire Trap', 'GREEN'),
    ('Vaal Fireball', 'BLUE'),
    ('Vaal Flameblast', 'BLUE'),
    ('Vaal Flesh Offering', 'BLUE'),
    ('Vaal Glacial Hammer', 'RED'),
    ('Vaal Grace', 'GREEN'),
    ('Vaal Ground Slam', 'RED'),
    ('Vaal Haste', 'GREEN'),
    ('Vaal Heavy Strike', 'RED'),
    ('Vaal Ice Nova', 'BLUE'),
    ('Vaal Immortal Call', 'RED'),
    ('Vaal Lightning Strike', 'GREEN'),
    ('Vaal Lightning Trap', 'BLUE'),
    ('Vaal Lightning Warp', 'BLUE'),
    ('Vaal Molten Shell', 'RED'),
    ('Vaal Power Siphon', 'BLUE'),
    ('Vaal Rain of Arrows', 'GREEN'),
    ('Vaal Reave', 'GREEN'),
    ('Vaal Righteous Fire', 'BLUE'),
    ('Vaal Spark', 'BLUE'),
    ('Vaal Storm Call', 'BLUE'),
    ('Vaal Summon Skeletons', 'BLUE'),
    ('Vaal Sweep', 'RED'),
    ('Vaal Spectral Throw', 'GREEN'),
    ('Vampiric Link', 'GREEN'),
    ('Vengeance', 'RED'),
    ('Impending Doom Support', 'BLUE'),
    ('Vigilant Strike', 'RED'),
    ('Viper Strike', 'GREEN'),
    ('Vitality', 'RED'),
    ('Volatile Dead', 'GREEN'),
    ('Voltaxic Burst', 'BLUE'),
    ('Vortex Mine', 'GREEN'),
    ('Vulnerability', 'RED'),
    ('Warlord''s Mark', 'RED'),
    ('Hydrosphere', 'BLUE'),
    ('Whirling Blades', 'GREEN'),
    ('Wild Strike', 'GREEN'),
    ('Wither', 'BLUE'),
    ('Wrath', 'BLUE'),
    ('Bodyswap of Sacrifice', 'BLUE'),
    ('Greater Multistrike Support', 'RED'),
    ('Greater Spell Echo Support', 'BLUE'),
    ('Galvanic Field of Intensity', 'BLUE'),
    ('Vaal Rejuvenation Totem', 'RED'),
    ('Raise Spectre of Transience', 'BLUE'),
    ('Vaal Smite', 'RED'),
    ('Vaal Reap', 'RED'),
    ('Explosive Trap of Magnitude', 'GREEN'),
    ('Wave of Conviction of Trarthus', 'BLUE'),
    ('Arc of Surging', 'BLUE'),
    ('Vaal Absolution', 'RED'),
    ('Greater Spell Cascade Support', 'BLUE'),
    ('Greater Ancestral Call Support', 'RED'),
    ('Vaal Flicker Strike', 'GREEN'),
    ('Greater Fork Support', 'GREEN'),
    ('Vaal Venom Gyre', 'GREEN'),
    ('Vaal Caustic Arrow', 'GREEN'),
    ('Summon Holy Relic of Conviction', 'BLUE'),
    ('Cleave of Rage', 'RED'),
    ('Rain of Arrows of Artillery', 'GREEN'),
    ('Elemental Hit of the Spectrum', 'GREEN'),
    ('Animate Weapon of Self Reflection', 'GREEN'),
    ('Cyclone of Tumult', 'GREEN'),
    ('Greater Unleash Support', 'BLUE'),
    ('Lancing Steel of Spraying', 'GREEN'),
    ('Animate Weapon of Ranged Arms', 'GREEN'),
    ('Greater Chain Support', 'GREEN'),
    ('Searing Bond of Detonation', 'RED'),
    ('Vaal Cleave', 'RED'),
    ('Shock Nova of Procession', 'BLUE'),
    ('Spark of Unpredictability', 'BLUE'),
    ('Spark of the Nova', 'BLUE'),
    ('Eye of Winter of Finality', 'BLUE'),
    ('Righteous Fire of Arcane Devotion', 'BLUE'),
    ('Glacial Cascade of the Fissure', 'BLUE'),
    ('Soulrend of the Spiral', 'BLUE'),
    ('Ground Slam of Earthshaking', 'RED'),
    ('Lacerate of Butchering', 'GREEN'),
    ('Icicle Mine of Fanning', 'BLUE'),
    ('Summon Carrion Golem of Hordes', 'BLUE'),
    ('Flameblast of Celerity', 'BLUE'),
    ('Penance Brand of Dissipation', 'BLUE'),
    ('Detonate Dead of Scavenging', 'GREEN'),
    ('Smite of Divine Judgement', 'RED'),
    ('Rain of Arrows of Saturation', 'GREEN'),
    ('Icicle Mine of Sabotage', 'BLUE'),
    ('Kinetic Blast of Clustering', 'BLUE'),
    ('Blight of Contagion', 'BLUE'),
    ('Summon Reaper of Eviscerating', 'BLUE'),
    ('Vaal Animate Weapon', 'GREEN'),
    ('Animate Guardian of Smiting', 'RED'),
    ('Detonate Dead of Chain Reaction', 'GREEN'),
    ('Firestorm of Pelting', 'BLUE'),
    ('Arc of Oscillating', 'BLUE'),
    ('Eye of Winter of Transience', 'BLUE'),
    ('Crackling Lance of Branching', 'BLUE'),
    ('Lightning Tendrils of Eccentricity', 'BLUE'),
    ('Boneshatter of Complex Trauma', 'RED'),
    ('Summon Flame Golem of the Meteor', 'RED'),
    ('Tornado of Elemental Turbulence', 'GREEN'),
    ('Ice Shot of Penetration', 'GREEN'),
    ('Summon Skeletons of Mages', 'BLUE'),
    ('Raise Zombie of Slamming', 'BLUE'),
    ('Summon Stone Golem of Safeguarding', 'RED'),
    ('Summon Carrion Golem of Scavenging', 'BLUE'),
    ('Void Sphere of Rending', 'BLUE'),
    ('Lightning Strike of Arcing', 'GREEN'),
    ('Hexblast of Contradiction', 'BLUE'),
    ('Summon Chaos Golem of the Maelström', 'BLUE'),
    ('Armageddon Brand of Recall', 'BLUE'),
    ('Flame Surge of Combusting', 'BLUE'),
    ('Forbidden Rite of Soul Sacrifice', 'BLUE'),
    ('Summon Reaper of Revenants', 'BLUE'),
    ('Earthshatter of Prominence', 'RED'),
    ('Mirror Arrow of Bombarding Clones', 'GREEN'),
    ('Boneshatter of Carnage', 'RED'),
    ('Volatile Dead of Seething', 'GREEN'),
    ('Blink Arrow of Bombarding Clones', 'GREEN'),
    ('Spectral Shield Throw of Trarthus', 'GREEN'),
    ('Dark Pact of Trarthus', 'BLUE'),
    ('Storm Burst of Repulsion', 'BLUE'),
    ('Ice Nova of Frostbolts', 'BLUE'),
    ('Ethereal Knives of the Massacre', 'GREEN'),
    ('Static Strike of Gathering Lightning', 'RED'),
    ('Summon Flame Golem of Hordes', 'RED'),
    ('Frostblink of Wintry Blast', 'BLUE'),
    ('Ball Lightning of Orbiting', 'BLUE'),
    ('Ice Spear of Splitting', 'BLUE'),
    ('Holy Flame Totem of Ire', 'RED'),
    ('Double Strike of Momentum', 'GREEN'),
    ('Reave of Refraction', 'GREEN'),
    ('Split Arrow of Splitting', 'GREEN'),
    ('Flame Dash of Return', 'BLUE'),
    ('Molten Strike of the Zenith', 'RED'),
    ('Poisonous Concoction of Bouncing', 'GREEN'),
    ('Incinerate of Expanse', 'BLUE'),
    ('Incinerate of Venting', 'BLUE'),
    ('Purifying Flame of Revelations', 'BLUE'),
    ('Blade Trap of Greatswords', 'GREEN'),
    ('Essence Drain of Desperation', 'BLUE'),
    ('Fire Trap of Blasting', 'GREEN'),
    ('Blink Arrow of Prismatic Clones', 'GREEN'),
    ('Siphoning Trap of Pain', 'BLUE'),
    ('Vaal Molten Strike', 'RED'),
    ('Raise Zombie of Falling', 'BLUE'),
    ('Toxic Rain of Sporeburst', 'GREEN'),
    ('Blade Blast of Dagger Detonation', 'GREEN'),
    ('Ball Lightning of Static', 'BLUE'),
    ('Vaal Arctic Armour', 'GREEN'),
    ('Explosive Trap of Shrapnel', 'GREEN'),
    ('Viper Strike of the Mamba', 'GREEN'),
    ('Storm Brand of Indecision', 'BLUE'),
    ('Lacerate of Haemorrhage', 'GREEN'),
    ('Firestorm of Meteors', 'BLUE'),
    ('Divine Ire of Disintegration', 'BLUE'),
    ('Lightning Trap of Sparking', 'BLUE'),
    ('Divine Ire of Holy Lightning', 'BLUE'),
    ('Perforate of Duality', 'RED'),
    ('Summon Raging Spirit of Enormity', 'BLUE'),
    ('Lightning Spire Trap of Overloading', 'BLUE'),
    ('Soulrend of Reaping', 'BLUE'),
    ('Summon Lightning Golem of Hordes', 'BLUE'),
    ('Sunder of Earthbreaking', 'RED'),
    ('Contagion of Transference', 'BLUE'),
    ('Bladefall of Volleys', 'GREEN'),
    ('Ethereal Knives of Lingering Blades', 'GREEN'),
    ('Dual Strike of Ambidexterity', 'GREEN'),
    ('Bladefall of Impaling', 'GREEN'),
    ('Tectonic Slam of Cataclysm', 'RED'),
    ('Flameblast of Contraction', 'BLUE'),
    ('Crackling Lance of Disintegration', 'BLUE'),
    ('Ice Crash of Cadence', 'RED'),
    ('Armageddon Brand of Volatility', 'BLUE'),
    ('Cremation of the Volcano', 'GREEN'),
    ('Sunder of Trarthus', 'RED'),
    ('Heavy Strike of Trarthus', 'RED'),
    ('Spectral Throw of Trarthus', 'GREEN'),
    ('Blight of Atrophy', 'BLUE'),
    ('Scourge Arrow of Menace', 'GREEN'),
    ('Kinetic Bolt of Fragmentation', 'BLUE'),
    ('Puncture of Shanking', 'GREEN'),
    ('Storm Rain of the Conduit', 'GREEN'),
    ('Summon Stone Golem of Hordes', 'RED'),
    ('Bear Trap of Skewers', 'GREEN'),
    ('Toxic Rain of Withering', 'GREEN'),
    ('Absolution of Inspiring', 'RED'),
    ('Power Siphon of the Archmage', 'BLUE'),
    ('Dominating Blow of Inspiring', 'RED'),
    ('Lightning Arrow of Electrocution', 'GREEN'),
    ('Penance Brand of Conduction', 'BLUE'),
    ('Barrage of Volley Fire', 'GREEN'),
    ('Perforate of Bloodshed', 'RED'),
    ('Infernal Blow of Immolation', 'RED'),
    ('Discharge of Misery', 'BLUE'),
    ('Creeping Frost of Floes', 'BLUE'),
    ('Orb of Storms of Squalls', 'BLUE'),
    ('Bane of Condemnation', 'BLUE'),
    ('Ice Nova of Deep Freeze', 'BLUE'),
    ('Vortex of Projection', 'BLUE'),
    ('Blade Trap of Laceration', 'GREEN'),
    ('Summon Chaos Golem of Hordes', 'BLUE'),
    ('Frost Bomb of Instability', 'BLUE'),
    ('Frost Bomb of Forthcoming', 'BLUE'),
    ('Lightning Tendrils of Escalation', 'BLUE'),
    ('Summon Skeletons of Archers', 'BLUE'),
    ('Explosive Concoction of Destruction', 'GREEN'),
    ('Lightning Spire Trap of Zapping', 'BLUE'),
    ('Hexblast of Havoc', 'BLUE'),
    ('Stormbind of Teleportation', 'BLUE'),
    ('Bladefall of Trarthus', 'GREEN'),
    ('Lightning Conduit of the Heavens', 'BLUE'),
    ('Scorching Ray of Immolation', 'BLUE'),
    ('Volatile Dead of Confinement', 'GREEN'),
    ('Glacial Hammer of Shattering', 'RED'),
    ('Galvanic Arrow of Energy', 'GREEN'),
    ('Contagion of Subsiding', 'BLUE'),
    ('Shockwave Totem of Authority', 'RED'),
    ('Earthquake of Amplification', 'RED'),
    ('Essence Drain of Wickedness', 'BLUE'),
    ('Caustic Arrow of Poison', 'GREEN'),
    ('Galvanic Arrow of Surging', 'GREEN'),
    ('Siege Ballista of Splintering', 'GREEN'),
    ('Shield Crush of the Chieftain', 'RED'),
    ('Consecrated Path of Endurance', 'RED'),
    ('Summon Ice Golem of Hordes', 'GREEN'),
    ('Blast Rain of Trarthus', 'GREEN'),
    ('Rage Vortex of Berserking', 'RED'),
    ('Pyroclast Mine of Sabotage', 'BLUE'),
    ('Leap Slam of Groundbreaking', 'RED'),
    ('Blade Blast of Unloading', 'GREEN'),
    ('Splitting Steel of Ammunition', 'GREEN'),
    ('Earthshatter of Fragility', 'RED'),
    ('Bladestorm of Uncertainty', 'RED'),
    ('Double Strike of Impaling', 'GREEN'),
    ('Artillery Ballista of Focus Fire', 'GREEN'),
    ('Cremation of Exhuming', 'GREEN'),
    ('Mirror Arrow of Prismatic Clones', 'GREEN'),
    ('Exsanguinate of Transmission', 'RED'),
    ('Vaal Ice Shot', 'GREEN'),
    ('Shrapnel Ballista of Steel', 'GREEN'),
    ('Tornado Shot of Cloudburst', 'GREEN'),
    ('Frost Blades of Katabasis', 'GREEN'),
    ('Ice Trap of Hollowness', 'GREEN'),
    ('Summon Ice Golem of Shattering', 'GREEN'),
    ('Flamethrower Trap of Stability', 'GREEN'),
    ('Cold Snap of Power', 'BLUE'),
    ('Spectral Throw of Materialising', 'GREEN'),
    ('Artillery Ballista of Cross Strafe', 'GREEN'),
    ('Frenzy of Onslaught', 'GREEN'),
    ('Shattering Steel of Ammunition', 'GREEN'),
    ('Vaal Firestorm', 'BLUE'),
    ('Storm Rain of the Fence', 'GREEN'),
    ('Blade Flurry of Incision', 'GREEN'),
    ('Blade Vortex of the Scythe', 'GREEN'),
    ('Charged Dash of Projection', 'GREEN'),
    ('Vaal Lightning Arrow', 'GREEN'),
    ('Seismic Trap of Swells', 'GREEN'),
    ('Flicker Strike of Power', 'GREEN'),
    ('Spectral Shield Throw of Shattering', 'GREEN'),
    ('Burning Arrow of Vigour', 'GREEN'),
    ('Wild Strike of Extremes', 'GREEN'),
    ('Vaal Blade Flurry', 'GREEN'),
    ('Chain Hook of Trarthus', 'RED'),
    ('Siege Ballista of Trarthus', 'GREEN'),
    ('Spectral Helix of Trarthus', 'GREEN'),
    ('Storm Call of Trarthus', 'BLUE')
ON CONFLICT (name) DO UPDATE SET color = EXCLUDED.color;
