root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/collector ./cmd/collector"
  bin = "./tmp/collector"
  delay = 1000
  exclude_dir = ["tmp", "vendor", "frontend", "db"]
  exclude_regex = ["_test\\.go$"]
  include_dir = ["cmd/collector", "internal/collector", "internal/db", "internal/price"]
  include_ext = ["go"]
  kill_delay = 500
  send_interrupt = true
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
