# Development environment override
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
  node:
    environment:
      APP_ENV: dev
