controllers:
    resource: ../src/Presentation/Controller/
    type: attribute

price_registry:
    resource: ../src/Presentation/PriceRegistry
    type: attribute

strategies:
    resource: ../src/Presentation/Strategies
    type: attribute
