-- Seed gem colors for 3.28 Mirage league gems identified from wiki icons
INSERT INTO gem_colors (name, color) VALUES
    ('Annihilation Support', 'RED'),
    ('Autoexertion', 'RED'),
    ('Automation', 'BLUE'),
    ('Blessed Call Support', 'RED'),
    ('Bloodsoaked Banner Support', 'RED'),
    ('Bonespire Support', 'RED'),
    ('Cast on Ward Break Support', 'GREEN'),
    ('Companionship Support', 'GREEN'),
    ('Conflagration', 'GREEN'),
    ('Congregation Support', 'BLUE'),
    ('Controlled Blaze Support', 'RED'),
    ('Cooldown Recovery Support', 'BLUE'),
    ('Corrupting Cry Support', 'RED'),
    ('Crushing Fist', 'RED'),
    ('Cull the Weak Support', 'GREEN'),
    ('Cursed Ground Support', 'BLUE'),
    ('Detonate Mines', 'BLUE'),
    ('Devour Support', 'BLUE'),
    ('Divine Blast', 'RED'),
    ('Divine Retribution', 'BLUE'),
    ('Divine Sentinel Support', 'RED'),
    ('Eclipse Support', 'WHITE'),
    ('Eldritch Blasphemy Support', 'BLUE'),
    ('Eviscerate', 'RED'),
    ('Excommunicate Support', 'RED'),
    ('Exemplar Support', 'BLUE'),
    ('Expert Retaliation Support', 'RED'),
    ('Fissure Support', 'RED'),
    ('Flamewood Support', 'RED'),
    ('Focused Channelling Support', 'BLUE'),
    ('Foulgrasp Support', 'BLUE'),
    ('Fresh Meat Support', 'BLUE'),
    ('Frigid Bond Support', 'BLUE'),
    ('Frostmage Support', 'BLUE'),
    ('Frozen Legion', 'RED'),
    ('Frozen Legion of Rallying', 'RED'),
    ('Glacial Shield Swipe', 'GREEN'),
    ('Gluttony Support', 'BLUE'),
    ('Greater Devour Support', 'BLUE'),
    ('Greater Kinetic Instability Support', 'BLUE'),
    ('Guardian''s Blessing Support', 'RED'),
    ('Hallow Support', 'RED'),
    ('Hex Bloom Support', 'BLUE'),
    ('Hexpass Support', 'BLUE'),
    ('Hextoad Support', 'BLUE'),
    ('Hiveborn Support', 'BLUE'),
    ('Holy Hammers', 'RED'),
    ('Holy Strike', 'RED'),
    ('Holy Sweep', 'RED'),
    ('Invention Support', 'GREEN'),
    ('Invert the Rules Support', 'BLUE'),
    ('Kinetic Fusillade', 'BLUE'),
    ('Kinetic Fusillade of Detonation', 'BLUE'),
    ('Kinetic Instability Support', 'BLUE'),
    ('Kinetic Rain', 'BLUE'),
    ('Kinetic Rain of Impact', 'BLUE'),
    ('Lethal Dose Support', 'GREEN'),
    ('Living Lightning Support', 'BLUE'),
    ('Locus Mine Support', 'GREEN'),
    ('Machinations Support', 'GREEN'),
    ('Manaforged Arrows Support', 'GREEN'),
    ('Minion Pact Support', 'BLUE'),
    ('Momentum Support', 'GREEN'),
    ('More Duration Support', 'RED'),
    ('Multiple Projectiles Support', 'GREEN'),
    ('Overexertion Support', 'RED'),
    ('Overheat Support', 'RED'),
    ('Overloaded Intensity Support', 'BLUE'),
    ('Pacifism Support', 'GREEN'),
    ('Portal', 'WHITE'),
    ('Prismatic Burst Support', 'BLUE'),
    ('Pyre Support', 'RED'),
    ('Returning Projectiles Support', 'GREEN'),
    ('Rupture Support', 'GREEN'),
    ('Sacred Wisps Support', 'BLUE'),
    ('Sacrifice Support', 'BLUE'),
    ('Sadism Support', 'GREEN'),
    ('Scornful Herald Support', 'BLUE'),
    ('Shield of Light', 'RED'),
    ('Somatic Shell', 'BLUE'),
    ('Spellblade Support', 'BLUE'),
    ('Swordstorm', 'RED'),
    ('Thunderstorm', 'GREEN'),
    ('Transfusion Support', 'RED'),
    ('Trauma Support', 'RED'),
    ('Unholy Trinity Support', 'GREEN'),
    ('Vaal Domination', 'RED'),
    ('Vaal Sacrifice Support', 'BLUE'),
    ('Vaal Temptation Support', 'RED'),
    ('Vaal Volcanic Fissure', 'RED'),
    ('Vengeful Cry', 'RED'),
    ('Void Shockwave Support', 'RED'),
    ('Voidstorm Support', 'GREEN'),
    ('Volatility Support', 'RED'),
    ('Volcanic Fissure', 'RED'),
    ('Volcanic Fissure of Snaking', 'RED'),
    ('Wall of Force', 'BLUE'),
    ('Windburst Support', 'GREEN')
ON CONFLICT (name) DO UPDATE SET color = EXCLUDED.color;
