ALTER TABLE gem_features ADD COLUMN sell_probability_factor DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE gem_features ADD COLUMN stability_discount DOUBLE PRECISION NOT NULL DEFAULT 1.0;

ALTER TABLE gem_signals ADD COLUMN risk_adjusted_value DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE gem_signals ADD COLUMN quick_sell_price DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE gem_signals ADD COLUMN sell_confidence TEXT NOT NULL DEFAULT '';
